"""Pytest shared fixtures for T2V module test suite."""

import json
import os
import shutil
import sys
from pathlib import Path
import pytest

# Ensure project root is in sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from adapters.mock_adapter import MockT2VAdapter
from engine.t2v_engine import T2VEngine
from schemas.t2v_request import T2VRequest


@pytest.fixture
def tmp_output_dir(tmp_path):
    """Provide an isolated temporary output directory for generated videos."""
    out_dir = tmp_path / "test_outputs"
    out_dir.mkdir(parents=True, exist_ok=True)
    yield out_dir
    # Cleanup
    shutil.rmtree(out_dir, ignore_errors=True)


@pytest.fixture
def mock_adapter(tmp_output_dir):
    """Provide a configured MockT2VAdapter instance targeting temp dir."""
    return MockT2VAdapter({"output_dir": str(tmp_output_dir)})


@pytest.fixture
def t2v_engine(tmp_output_dir):
    """Provide a T2VEngine instance with mock provider."""
    return T2VEngine(provider="mock", config={"output_dir": str(tmp_output_dir)})


@pytest.fixture
def sample_valid_request():
    """A standard valid generation request dict."""
    return {
        "request_id": "pytest_valid_001",
        "prompt": "A warm sunrise over a quiet lake with mist hovering over the water.",
        "duration_seconds": 5,
        "fps": 16,
        "resolution": "832x480",
        "model": "Wan2.2-T2V-A14B",
        "provider": "mock",
    }


@pytest.fixture
def sample_minimal_request():
    """A minimal valid request with only prompt and request_id."""
    return {
        "request_id": "pytest_minimal_001",
        "prompt": "A red leaf falling from an autumn branch.",
    }


@pytest.fixture
def manifest_data():
    """Load the master manifest.json generated by fixture pipeline."""
    manifest_path = PROJECT_ROOT / "mock_data" / "manifest.json"
    if not manifest_path.exists():
        pytest.skip("mock_data/manifest.json not found. Run generate_fixtures.py first.")
    with open(manifest_path, "r", encoding="utf-8") as f:
        return json.load(f)
